name = "Cortex"
uuid = "39612bbb-57ff-4bee-a8f8-6b0371679005"
authors = ["Bagaev Dmitry <bvdmitri@gmail.com> and contributors"]
version = "0.2.0"

[weakdeps]
BipartiteFactorGraphs = "b30351d1-6332-4c89-82f4-633fdf76981a"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"

[extensions]
BipartiteFactorGraphsExt = "BipartiteFactorGraphs"
GraphVizExt = "GraphViz"

[compat]
Aqua = "0.8"
BenchmarkTools = "1.6"
BipartiteFactorGraphs = "1.0.0"
GraphViz = "0.2.0"
JET = "0.9, 0.10"
Random = "1.10"
Reexport = "1.2"
StableRNGs = "1.0"
Test = "1.10"
TestItemRunner = "1.1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BipartiteFactorGraphs = "b30351d1-6332-4c89-82f4-633fdf76981a"
GraphViz = "f526b714-d49f-11e8-06ff-31ed36ee7ee0"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Aqua", "BenchmarkTools", "BipartiteFactorGraphs", "GraphViz", "JET", "Random", "Reexport", "StableRNGs", "Test", "TestItemRunner"]
